Repository ianstormtaylor/react-values, pull requests merged in 2018-07, with the labels that each got.

#12 Fix clone values
  src/components/any-value.js
  src/components/array-value.js
  src/components/date-value.js
  src/components/map-value.js
  src/components/set-value.js
  test/components/array-value.js
  test/components/date-value.js
  test/components/map-value.js
  test/components/set-value.js
Labels: improvement

#13 refactor transforms to be defined more succinctly
  src/components/any-value.js
  src/components/array-value.js
  src/components/boolean-value.js
  src/components/date-value.js
  src/components/map-value.js
  src/components/number-value.js
  src/components/set-value.js
  src/components/string-value.js
  src/utils/defaults.js
  src/utils/proxy.js
  src/utils/render.js
Labels: debt

#15 add `disabled` prop
  docs/guide.md
  docs/reference.md
  src/components/any-value.js
  test/components/any-value.js
Labels: feature

#16 Small typo
  Readme.md
Labels: docs

#17 Add missing `disabled` prop in guide
  docs/guide.md
Labels: docs

#19 add `disabled` as a render prop
  src/components/any-value.js
  test/components/any-value.js
Labels: improvement

#23 Add _isMounted flag
  src/components/any-value.js
Labels: bug

#28 add <ObjectValue> component
  Readme.md
  docs/reference.md
  src/components/object-value.js
  src/index.js
  test/components/object-value.js
  test/index.js
Labels: feature
